In [1]:
import pandas as pd
import numpy as np
import scipy.stats
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
user_df = pd.read_json("../data/MOOCCube/entities/user.json",lines=True)
data_train = []
data_test = []
for index, row in user_df.iterrows():
    user_id = row["id"]
    courses = row["course_order"]
    if len(courses) > 5:

        index_partition = int(len(courses) * 0.75)

        courses_1 = courses[:index_partition]
        courses_2 = courses[index_partition:]
        
        for course in courses_1:
            data_train.append({
                "user_id":user_id,
                "course_id":course,
                "view":1
            })
            
        for course in courses_2:
            data_test.append({
                "user_id":user_id,
                "course_id":course,
                "view":1
            })

In [3]:
df_train = pd.DataFrame(data_train)
df_test = pd.DataFrame(data_test)

In [4]:
df_train.shape

(153049, 3)

In [5]:
matrix = df_train.pivot_table(index='user_id', columns='course_id', values='view')
matrix.head()

course_id,C_course-v1:ACCA+FA1_X+2019_T1,C_course-v1:ACCA+FA1_X+sp,C_course-v1:ACCA+FA1_X_en+2019_T1,C_course-v1:ACCA+FA2_X+2019_T1,C_course-v1:ACCA+FA2_X+sp,C_course-v1:ACCA+FA2_X_en+2019_T1,C_course-v1:ACCA+MA1_X+2019_T1,C_course-v1:ACCA+MA1_X+sp,C_course-v1:ACCA+MA1_X_en+2019_T1,C_course-v1:ACCA+MA2_X+2019_T1,...,C_course-v1:nxu+2018122711+2019_T1,C_course-v1:nxu+2018122712+2019_T1,C_course-v1:nxu+2018122713+2019_T1,C_course-v1:qdu+2018122608X+2018_T2,C_course-v1:qhnu+20181212x+2018_T2,C_course-v1:qhnu+20181212x+2019_T1,C_course-v1:rcoe+mooc103+2019_T1,C_course-v1:shsmu+shsmu001+2019_T1,C_course-v1:snnu+20180920X+2019_T1,C_course-v1:xuetangX+MOOC102+2019_T1
user_id,,,,,,,,,,,,,,,,,,,,,
U_10000168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U_10000205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U_10000338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U_10000415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U_10000491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
matrix = matrix.fillna(0)
matrix.head()

course_id,C_course-v1:ACCA+FA1_X+2019_T1,C_course-v1:ACCA+FA1_X+sp,C_course-v1:ACCA+FA1_X_en+2019_T1,C_course-v1:ACCA+FA2_X+2019_T1,C_course-v1:ACCA+FA2_X+sp,C_course-v1:ACCA+FA2_X_en+2019_T1,C_course-v1:ACCA+MA1_X+2019_T1,C_course-v1:ACCA+MA1_X+sp,C_course-v1:ACCA+MA1_X_en+2019_T1,C_course-v1:ACCA+MA2_X+2019_T1,...,C_course-v1:nxu+2018122711+2019_T1,C_course-v1:nxu+2018122712+2019_T1,C_course-v1:nxu+2018122713+2019_T1,C_course-v1:qdu+2018122608X+2018_T2,C_course-v1:qhnu+20181212x+2018_T2,C_course-v1:qhnu+20181212x+2019_T1,C_course-v1:rcoe+mooc103+2019_T1,C_course-v1:shsmu+shsmu001+2019_T1,C_course-v1:snnu+20180920X+2019_T1,C_course-v1:xuetangX+MOOC102+2019_T1
user_id,,,,,,,,,,,,,,,,,,,,,
U_10000168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
U_10000205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
U_10000338,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
U_10000415,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
U_10000491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
user_correlation = matrix.T.corr(method='pearson', min_periods=1)

In [8]:
similar_users = user_correlation["U_10000205"].sort_values(ascending=False)[1:11]
df = pd.DataFrame(similar_users)

In [9]:
df.head()
for index, row in df.iterrows():
    print(row["U_10000205"])
    print(index)

0.5441271493535857
U_1966725
0.5441271493535855
U_2013352
0.495620437956205
U_8475699
0.4956204379562047
U_8863612
0.49562043795620453
U_471472
0.4273156230155508
U_1018007
0.4040829209128268
U_36008
0.40408292091282677
U_8550243
0.40408292091282677
U_2576601
0.40408292091282677
U_22772

In [10]:
user_df.head(

)

,id,name,course_order,enroll_time
0,U_7001215,李喜锋,"[C_course-v1:TsinghuaX+00740043_2x_2015_T2+sp,...","[2017-05-01 11:07:53, 2017-05-17 10:07:17, 201..."
1,U_10402446,五元香,"[C_course-v1:TsinghuaX+00510888X+2019_T1, C_co...","[2019-06-14 08:50:04, 2019-01-04 20:36:07]"
2,U_10359065,魏珊,"[C_course-v1:TsinghuaX+00612642X+sp, C_course-...","[2019-01-18 21:19:56, 2019-01-14 21:54:54]"
3,U_7423998,郭海滨,"[C_course-v1:TsinghuaX+30240184_2X+sp, C_cours...","[2017-08-16 10:38:11, 2018-07-01 18:24:24, 201..."
4,U_545306,李其艳,"[C_course-v1:TsinghuaX+20430064_2X+sp, C_cours...","[2018-09-05 15:40:40, 2019-02-28 10:08:49, 201..."

In [62]:
def make_recomendation(user,dfs,matrix,num_rec=10):
    similar_users = matrix[user].sort_values(ascending=False)[1:20]
    df = pd.DataFrame(similar_users)
    # print(df.head())
    similar_users_ids = []
    for index, row in df.iterrows():
        similar_users_ids.append({"user_id":index,"relevance":row[user]})
    courses_taken=dfs.loc[dfs['id'] == user, 'course_order'].iloc[0]
    recomendation = {}
    for user_id in similar_users_ids:
        result = dfs.loc[dfs['id'] == user_id["user_id"], 'course_order'].iloc[0]
        set1 = set(courses_taken)
        set2 = set(result)
        courses_not_taken = set1-set2
        for j in courses_not_taken:
            cant = recomendation.get(j,0)
            recomendation[j]=cant+user_id["relevance"]
    final = []
    for i in recomendation:
        final.append({
            "course_id":i,
            "quantity":recomendation[i]/20
        })
    sorted_data = sorted(final, key=lambda x: x['quantity'])[::-1]
    return sorted_data[:num_rec]
        
make_recomendation("U_10000205",user_df,user_correlation)

[{'course_id': 'C_course-v1:TsinghuaX+60240013X+sp',
  'quantity': 0.41277546037290413},
 {'course_id': 'C_course-v1:GZHU+20180718001+2019_T1',
  'quantity': 0.41277546037290413},
 {'course_id': 'C_course-v1:UST+UST001+sp', 'quantity': 0.41277546037290413},
 {'course_id': 'C_course-v1:NCTU+wghx+2017_T1',
  'quantity': 0.38556910290522495},
 {'course_id': 'C_course-v1:TsinghuaX+30240184+sp',
  'quantity': 0.351001387130844},
 {'course_id': 'C_course-v1:TsinghuaX+70660542X+2015_T2',
  'quantity': 0.31795445334626293},
 {'course_id': 'C_course-v1:TsinghuaX+30240243X+sp',
  'quantity': 0.22924781792409266},
 {'course_id': 'C_course-v1:TsinghuaX+30150153X+sp',
  'quantity': 0.08781879560460328},
 {'course_id': 'C_course-v1:TsinghuaX+70150023X+sp',
  'quantity': 0.04741050351332062}]

In [67]:
grouped = df_test.groupby('user_id')['course_id'].apply(list).reset_index()
user_course_list = grouped.to_dict(orient='records')
# print(user_course_list[12])

def evaluate():
    cont = 0
    results = []
    for row in user_course_list:
        recomendations = make_recomendation(row["user_id"],user_df,user_correlation,num_rec=len(row["course_id"]))
        recomended_courses = [d["course_id"] for d in recomendations]
        set1 = set(row["course_id"])
        set2 = set(recomended_courses)
        results.append({
            "user_id":row["user_id"],
            "num_recomendations":len(row["course_id"]),
            "evaluate":len(row["course_id"]),
            "matches":len(set1.intersection(set2))
        })
        
        cont = 1 + cont
        print(cont)
    return results  

    
evaluate()

{'user_id': 'U_10000168', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
1
{'user_id': 'U_10000205', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
2
{'user_id': 'U_10000338', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
3
{'user_id': 'U_10000415', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
4
{'user_id': 'U_10000491', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
5
{'user_id': 'U_1000063', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
6
{'user_id': 'U_10000658', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
7
{'user_id': 'U_10001302', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
8
{'user_id': 'U_10001348', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
9
{'user_id': 'U_1000149', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
10
{'user_id': 'U_10001784', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
11
{'user_id': 'U_10002175', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
12
{'user_id': 'U_10002610', 'num_recomendations': 5, 'evaluate': 5, 'matches': 2}
13
{'user_id': 'U_1000541', 'num_recomendations': 4, 'evaluate': 4, 'matches': 2}
14
{'user_id': 'U_1000603', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
15
{'user_id': 'U_1000752', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
16
{'user_id': 'U_1000850', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
17
{'user_id': 'U_10008612', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
18
{'user_id': 'U_10009424', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
19
{'user_id': 'U_10009468', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
20
{'user_id': 'U_10017217', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
21
{'user_id': 'U_10017438', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
22
{'user_id': 'U_10017915', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
23
{'user_id': 'U_10017973', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
24
{'user_id': 'U_10018930', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
25
{'user_id': 'U_10019770', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
26
{'user_id': 'U_10019785', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
27
{'user_id': 'U_10020238', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
28
{'user_id': 'U_10020438', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
29
{'user_id': 'U_10020747', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
30
{'user_id': 'U_10021012', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
31
{'user_id': 'U_10021027', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
32
{'user_id': 'U_10021046', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
33
{'user_id': 'U_10021286', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
34
{'user_id': 'U_10021673', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
35
{'user_id': 'U_10021722', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
36
{'user_id': 'U_10023829', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
37
{'user_id': 'U_10023837', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
38
{'user_id': 'U_10024003', 'num_recomendations': 3, 'evaluate': 3, 'matches': 3}
39
{'user_id': 'U_10024070', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
40
{'user_id': 'U_10024265', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
41
{'user_id': 'U_10025408', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
42
{'user_id': 'U_10025608', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
43
{'user_id': 'U_10025906', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
44
{'user_id': 'U_10025962', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
45
{'user_id': 'U_10025999', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
46
{'user_id': 'U_10026175', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
47
{'user_id': 'U_10026492', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
48
{'user_id': 'U_1002679', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
49
{'user_id': 'U_1002720', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
50
{'user_id': 'U_10027644', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
51
{'user_id': 'U_1002765', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
52
{'user_id': 'U_10028032', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
53
{'user_id': 'U_1002971', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
54
{'user_id': 'U_1003076', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
55
{'user_id': 'U_10030787', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
56
{'user_id': 'U_10031580', 'num_recomendations': 10, 'evaluate': 10, 'matches': 7}
57
{'user_id': 'U_10032663', 'num_recomendations': 5, 'evaluate': 5, 'matches': 2}
58
{'user_id': 'U_10032755', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
59
{'user_id': 'U_10032843', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
60
{'user_id': 'U_10033130', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
61
{'user_id': 'U_10033444', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
62
{'user_id': 'U_10033471', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
63
{'user_id': 'U_10033511', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
64
{'user_id': 'U_10033590', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
65
{'user_id': 'U_10033809', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
66
{'user_id': 'U_10034193', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
67
{'user_id': 'U_10034749', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
68
{'user_id': 'U_10035534', 'num_recomendations': 4, 'evaluate': 4, 'matches': 3}
69
{'user_id': 'U_10035631', 'num_recomendations': 3, 'evaluate': 3, 'matches': 3}
70
{'user_id': 'U_10036091', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
71
{'user_id': 'U_10036371', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
72
{'user_id': 'U_10036469', 'num_recomendations': 5, 'evaluate': 5, 'matches': 3}
73
{'user_id': 'U_10036482', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
74
{'user_id': 'U_10037941', 'num_recomendations': 4, 'evaluate': 4, 'matches': 3}
75
{'user_id': 'U_10038946', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
76
{'user_id': 'U_10038994', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
77
{'user_id': 'U_10039307', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
78
{'user_id': 'U_10039545', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
79
{'user_id': 'U_10040189', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
80
{'user_id': 'U_10040641', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
81
{'user_id': 'U_10041727', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
82
{'user_id': 'U_10041835', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
83
{'user_id': 'U_10041882', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
84
{'user_id': 'U_10042137', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
85
{'user_id': 'U_10042367', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
86
{'user_id': 'U_1004242', 'num_recomendations': 3, 'evaluate': 3, 'matches': 3}
87
{'user_id': 'U_10042494', 'num_recomendations': 4, 'evaluate': 4, 'matches': 3}
88
{'user_id': 'U_100427', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
89
{'user_id': 'U_10042737', 'num_recomendations': 4, 'evaluate': 4, 'matches': 2}
90
{'user_id': 'U_10042779', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
91
{'user_id': 'U_10042832', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
92
{'user_id': 'U_10042894', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
93
{'user_id': 'U_10043060', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
94
{'user_id': 'U_100434', 'num_recomendations': 3, 'evaluate': 3, 'matches': 1}
95
{'user_id': 'U_10044000', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
96
{'user_id': 'U_100441', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
97
{'user_id': 'U_10044873', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
98
{'user_id': 'U_10044899', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
99
{'user_id': 'U_10045141', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
100
{'user_id': 'U_10045238', 'num_recomendations': 3, 'evaluate': 3, 'matches': 3}
101
{'user_id': 'U_10046378', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
102
{'user_id': 'U_10046493', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
103
{'user_id': 'U_10046970', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
104
{'user_id': 'U_10047019', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
105
{'user_id': 'U_10047472', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
106
{'user_id': 'U_10047697', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
107
{'user_id': 'U_10049711', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
108
{'user_id': 'U_10050453', 'num_recomendations': 3, 'evaluate': 3, 'matches': 2}
109
{'user_id': 'U_10050522', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
110
{'user_id': 'U_10050868', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
111
{'user_id': 'U_10051274', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
112
{'user_id': 'U_10051367', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
113
{'user_id': 'U_10051596', 'num_recomendations': 2, 'evaluate': 2, 'matches': 2}
114
{'user_id': 'U_10051655', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
115
{'user_id': 'U_100520', 'num_recomendations': 8, 'evaluate': 8, 'matches': 4}
116
{'user_id': 'U_10052298', 'num_recomendations': 2, 'evaluate': 2, 'matches': 1}
117
{'user_id': 'U_10052314', 'num_recomendations': 2, 'evaluate': 2, 'matches': 0}
118